---
- name: Load CentOS stuff
  include: CentOS_6.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

# - name: Load CentOS 7 stuff
#   include: CentOS_7.yml
#   when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == 7

- name: Load Ubuntu stuff
  include: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
